[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[plugins]]
  package = "netlify-plugin-minify-html"
[plugins.inputs]
  contexts = [
    'production',
    'branch-deploy',
    'deploy-preview'
  ]
  [plugins.inputs.minifierOptions]
    removeComments = true
    collapseBooleanAttributes= true
    collapseInlineTagWhitespace = true
    collapseWhitespace=true
    minifyCSS=true
    minifyURLs=true
    minifyJS=true
    removeTagWhitespace=true